#!/bin/bash

cd $HOME
git clone -q --recursive https://github.com/luvit/lit LitSrc
git clone -q --recursive https://github.com/luvit/luvi LuviSrc
cd LuviSrc
PREFIX=/usr make -s regular
PREFIX=/usr make -s
mv build/luvi ..
cd ..
rm -rf LuviSrc
cd LitSrc
../luvi . -- make .
mv lit ..
cd ..
rm -rf LitSrc
./lit make github://luvit/luvit
mv lit luvi luvit $HOME/.local/bin
