#[
  Author: Miqueas Martinez (https://github.com/Miqueas)
  Co-Author: Nelson "darltrash" López (https://github.com/darltrash)
  Date: 2020/09/12
  Git Repository: https://github.com/Miqueas/Logit

  zlib License

  Copyright (c) 2020 - 2022 Miqueas Martinez

  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
      claim that you wrote the original software. If you use this software
      in a product, an acknowledgment in the product documentation would be
      appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
      misrepresented as being the original software.

    3. This notice may not be removed or altered from any source
      distribution.
]#

import std/times
from std/os import getTempDir
from std/strutils import join

type
  LogKind* = enum
    OTHER,
    TRACE,
    DEBUG,
    INFO,
    WARN,
    ERROR,
    FATAL
  Logit* = object
    path: string
    namespace: string
    fileSuffix: string
    enableFile: bool
    defaultLevel: LogKind
    enableConsole: bool

const FMT = (
  FileName: "%s_%s.log",
  Out: (
    File: "%s [%s %s] %s@%s: %s",
    Console: e(2) & "%s [" & e(0,1) & "%s %s%s" & e(0,2) & "] %s@%s:" & e(0) & " %s"
  )
)

proc e(n: varargs[int]): string =
  return '\e' & '[' & join(n, ";") & 'm'

proc newLogit*(path = getTempDir(), name = "Logit", level = OTHER, console = false, file = true, suffix = ""): Logit =
  var o = Logit()
  o.path = path
  o.namespace = name
  o.fileSuffix = suffix
  o.enableFile = file
  o.defaultLevel = level
  o.enableConsole = console

  let
    header = "AUTOGENERATED BY LOGIT"
    time = now()
    #file = open()

  return o